feat: setup VPC and associated endpoint for accessing the network
aws-samples/cdk-hyperledger-fabric-network pull request #5
Opened 2022-01-26 18:46 UTC by vponselvan

#### Feature:  
- Creates VPC and associated endpoint for accessing the network with an option of using an existing VPC.
#### Update:  
- Removed the above feature from the list and added tags on README

2022-01-30 19:17 UTC, lordjabez requested changes
I suggest renaming the `vpc-endpoint.ts` to just `vpc.ts` since it's more broad than creating just the endpoint.

2022-01-30 19:17 UTC, lordjabez commented on src/vpc-endpoint.ts
> +
I don't think we need to expose the service name, but we probably do want to expose the vpcEndpoint itself.

2022-01-30 19:17 UTC, lordjabez commented on src/vpc-endpoint.ts
> +  public readonly vpcProps?: ec2.VpcProps;
Would any user of this construct need to have these props reflected back out, since the VPC itself is a property?

2022-01-30 19:17 UTC, lordjabez commented on src/vpc-endpoint.ts
> +  readonly existingVpc?: ec2.IVpc;
I want to think a little harder about these names, to ensure they're clear. Before we merge, what I'd recommend is coding up an example usage of this construct along with a Lambda that integrates with it. Let's do that with this repo: https://github.com/aws-samples/amazon-managed-blockchain-document-ledger.

2022-02-12 17:06 UTC, vponselvan commented
Updated the pull request with the new changes. Rewritten the logic for the VPC and endpoint creation.

2022-02-21 18:08 UTC, lordjabez approved these changes

2022-02-21 18:08 UTC, lordjabez commented on src/network.ts
> +  readonly client?: client.HyperledgerFabricClientProps;
I like the term `client` as it describes the purpose of the network, and avoids overloading the term "network".

2022-02-21 19:56 UTC, merged