feat: Enroll admin and store creds on SecretsManager
aws-samples/cdk-hyperledger-fabric-network pull request #7
Opened 2022-03-07 17:48 UTC by vponselvan

Feature:

    Enroll admin using the Fabric CA Client SDK and store credentials on SecretsManager

Update:

    Add S3 endpoint for accessing the TLS cert
    Enable private DNS on the VPC endpoint

2022-03-15 01:45 UTC, lordjabez requested changes
@vponselvan we're getting close here, just a few suggestions.

2022-03-15 01:45 UTC, lordjabez commented on src/identity-resources.ts
> +// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
What do you think about just naming this file `identity.ts` for simplicity and to match the single word pattern of the other source files?

2022-03-15 15:55 UTC, vponselvan commented on README.md
> -*  Enroll users, storing their credentials in Secrets Manager
Sure, I'll add it. I realized that later yesterday.

2022-03-15 15:55 UTC, vponselvan commented on src/user.ts
> +  /**
My bad, I'll fix the property. I added the password cause to create a User object on the fabric sdk, it needs it along with cert and the private key. But, I checked the sdk code right now and it just sets the password to the object and doesn't do anything else with it. So, I'll remove it.

2022-04-01 01:30 UTC, closed without merging

2022-04-10 14:44 UTC, lordjabez commented
This branch was merged manually along with some small cleanups.